export const products = [
  {
    id: "1",
    title: "Zapatillas Runing Under Armor",
    price: 3400,
    stock: 10,
    imageUrl:
      "https://media.istockphoto.com/id/1321017606/es/foto/camisetas-y-camisetas-deportivas-multicolores-sin-mangas.jpg?s=1024x1024&w=is&k=20&c=O8PbT6gihCSUbGu1LnSatjkdTrrQTaes0DEAtHGvsf8=",
    description: "Negras",
    category: "Hombre",
  },
  {
    id: "2",
    title: "Camisetas fit Under Armor",
    price: 3000,
    stock: 10,
    imageUrl: "",
    description: "Con la mejor tecnologia",
    category: "Hombre",
  },
  {
    id: "3",
    title: "Zapatillas runing Under Armor",
    price: 3500,
    stock: 10,
    imageUrl: "",
    description: "Blancas",
    category: "Mujer",
  },
  {
    id: "4",
    title: "Calza Under Armor",
    price: 2500,
    stock: 10,
    imageUrl: "",
    description: "Gris",
    category: "Mujer",
  },
  {
    id: "5",
    title: "Zapatillas runing Under Armor",
    price: 3500,
    stock: 10,
    imageUrl: "",
    description: "Blancas",
    category: "Niños",
  },
  {
    id: "6",
    title: "Calza Under Armor",
    price: 2500,
    stock: 10,
    imageUrl: "",
    description: "Gris",
    category: "Niños",
  },
];
